name: lomi
description: A new Flutter project.
publish_to: "none"
version: 2.1.0+33

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  #font_awesome:
  #google_fonts:
  line_icons: ^2.0.0
  font_awesome_flutter: ^10.4.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  google_sign_in: ^6.0.2
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+1
  cloud_firestore: ^4.5.0
  go_router: ^6.5.5
  geolocator: ^10.0.0
  cached_network_image: ^3.2.3
  #geoflutterfire:
  flutter_geo_hash: ^0.0.4
  swipe_cards: ^2.0.0+1
  #pay: ^1.1.1
  twitter_login: ^4.4.0
  geoflutterfire:
    path: packages/geoflutterfire/

  appinio_swiper: ^2.0.2
  swipable_stack: ^2.0.0
  in_app_purchase: ^3.1.10
  geocoding: ^2.1.0
  connectivity_plus: ^4.0.2
  hydrated_bloc: ^9.1.2
  path_provider: ^2.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.1

  change_app_package_name: ^1.1.0
  flutter_image_compress: ^2.0.4
  google_mobile_ads: ^5.2.0
  #google_fonts: ^6.0.0
  flutter_advanced_switch: ^3.0.1
  full_screen_image: ^2.0.0
  slide_countdown: ^0.6.0
  flutter_local_notifications: ^18.0.0
  flutter_screenutil: ^5.7.0
  rxdart: ^0.27.7
  firebase_remote_config: ^4.3.3
  version: ^3.0.2
  firebase_analytics: ^10.6.3
  url_launcher: ^6.1.10

  # webview_flutter: ^4.5.0
  webview_flutter: ^1.0.5
  firebase_messaging: ^14.7.9
  blur: ^3.1.0
  #workmanager: ^0.5.2
  flutter_background_service: ^5.0.1
  google_mlkit_image_labeling: ^0.12.0
  google_mlkit_face_detection: ^0.11.0

dependency_overrides:
  # angular: ">=0.9.10"
  webview_flutter_wkwebview: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    #- assets/images/girls/
    - assets/icons/
  fonts:
    - family: Proxima
      fonts:
        - asset: assets\fonts\Proxima-Nova-Black.otf
        - asset: assets\fonts\Proxima-Nova-Bold.otf
        - asset: assets\fonts\Proxima-Nova-Extrabold.otf
        - asset: assets\fonts\Proxima-Nova-Thin.otf
        - asset: assets\fonts\ProximaNova-Regular.otf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
